//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class catalago_tipo_horas_extras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalago_tipo_horas_extras()
        {
            this.horas_extras = new HashSet<horas_extras>();
        }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo debe contener solo números")]
        public int Id_Hora_Extra { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]*$", ErrorMessage = "El campo debe contener solo letras")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9.]*$", ErrorMessage = "El campo debe contener solo números")]
        public decimal Porcentaje { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horas_extras> horas_extras { get; set; }
    }
}
