//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class empleado
    {
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo solo permite numeros")]
        public int Id_Empleado { get; set; }



        [Required(ErrorMessage = "El campo es obligatorio")]
        public System.DateTime Fecha_Ingreso { get; set; }

        [RegularExpression(@"^\d+(\.\d+)?(,\d+)?$", ErrorMessage = "El campo solo permite números, puntos y comas")]
        [Required(ErrorMessage = "El campo es obligatorio")]
        public decimal Salario { get; set; }


        public long Persona_Cedula { get; set; }

        public int Jefatura_Id_Empleado { get; set; }

        public virtual persona persona { get; set; }
    }
}
