//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class horas_extras
    {
        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo debe contener solo números")]
        public int Id_Horas { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo debe contener solo números")]
        public int Cantidad_Horas_Extras { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public System.DateTime Fecha_Horas_Trabajadas { get; set; }
        public int Empleados_Id_Empleado { get; set; }
        public int Catalago_Tipo_Horas_Extras_Id_Hora_Extra { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9.]*$", ErrorMessage = "El campo debe contener solo números")]
        public float Monto { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual catalago_tipo_horas_extras catalago_tipo_horas_extras { get; set; }
    }
}
