//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class incapacidade
    {
        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo debe contener solo números")]
        public int idIncapacidades { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public System.DateTime Fecha_Inicio { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public System.DateTime Fecha_Fin { get; set; }
        public decimal Monto_Incapacidad { get; set; }
        public int Empleados_Id_Empleado { get; set; }
        public int IdTipoIncapacidad { get; set; }

        public virtual catalogo_tipo_incapacidades catalogo_tipo_incapacidades { get; set; }
    }
}
