//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.direccions = new HashSet<direccion>();
            this.empleados = new HashSet<empleado>();
            this.telefonoes = new HashSet<telefono>();
        }

        [Required(ErrorMessage = "La cédula es obligatoria")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo debe contener solo números")]
        [Range(100000000, 999999999999, ErrorMessage = "La cédula debe tener al menos 9 dígitos o un maximo de 12 si es extranjero")]
        public long Cedula { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]*$", ErrorMessage = "El nombre debe contener solo letras")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]*$", ErrorMessage = "El primer apellido debe contener solo letras")]
        public string Apeliido1 { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]*$", ErrorMessage = "El segundo apellido debe contener solo letras")]
        public string Apellido2 { get; set; }


        [Required(ErrorMessage = "El campo es obligatorio")]
        public DateTime Fecha_Nacimiento { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public int Catalago_Cedula_IdCatalago_Cedula { get; set; }
    
        public virtual catalago_cedula catalago_cedula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<direccion> direccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefono> telefonoes { get; set; }
    }
}
