//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class planilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public planilla()
        {
            this.detalles_planilla = new HashSet<detalles_planilla>();
        }
    
        public int Id_Planilla { get; set; }
        public System.DateTime Fecha { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9.]*$", ErrorMessage = "El campo debe contener solo números")]
        public decimal Horas_Laboradas { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public int Catalago_Deducciones_idCatalago_Deducciones { get; set; }
        public decimal Total_Neto { get; set; }
        public int Empleados_Id_Empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_planilla> detalles_planilla { get; set; }
    }
}
