//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class provincia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provincia()
        {
            this.cantons = new HashSet<canton>();
        }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El campo debe contener solo n˙meros")]
        public int idProvincia { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [RegularExpression("^[a-zA-Z·ÈÌÛ˙¡…Õ”⁄Ò—¸‹ ]*$", ErrorMessage = "El campo debe contener solo letras")]
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canton> cantons { get; set; }
    }
}
