//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_de_permiso_colaborador
    {
        public int Id_Permiso { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public int Empleados_Id_Empleado { get; set; }
        public int IdTipoPermiso { get; set; }
        public Nullable<bool> Abrobado { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual catalogo_control_permisos_colaborador catalogo_control_permisos_colaborador { get; set; }
    }
}
