//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public int idDireccion { get; set; }
        public string Otras_sennas { get; set; }
        public int Distrito_idDistrito { get; set; }
        public int Distrito_Canton_idCanton { get; set; }
        public int Distrito_Canton_Provincia_idProvincia { get; set; }
        public long Persona_Cedula { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual persona persona { get; set; }
    }
}
