//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int Id_Empleado { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public decimal Salario { get; set; }
        public long Persona_Cedula { get; set; }
        public int Jefatura_Id_Empleado { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
