//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class incapacidade
    {
        public int idIncapacidades { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public decimal Monto_Incapacidad { get; set; }
        public int Empleados_Id_Empleado { get; set; }
        public int IdTipoIncapacidad { get; set; }
    
        public virtual catalogo_tipo_incapacidades catalogo_tipo_incapacidades { get; set; }
    }
}
