//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquidacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public liquidacion()
        {
            this.detalles_liquidacion = new HashSet<detalles_liquidacion>();
        }
    
        public int Id_Liquidacion { get; set; }
        public System.DateTime Fecha_salida { get; set; }
        public int Dias_Preaviso { get; set; }
        public int Id_Tipo_Liquidacion { get; set; }
        public int Empleados_Id_Empleado { get; set; }
        public int Catalago_Tipo_Liquidacion_Id_Tipo_Liquidacion { get; set; }
        public decimal Monto { get; set; }
    
        public virtual catalago_tipo_liquidacion catalago_tipo_liquidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_liquidacion> detalles_liquidacion { get; set; }
    }
}
